// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function let_(pr, cb) {
  return pr.then(Curry.__1(cb));
}

var Async = {
  let_: let_
};

exports.Async = Async;
/* No side effect */
